OBJS += obj/util/libms_part0.o \
		obj/util/libms_part1.o \
		obj/util/libms_part2.o \
		obj/util/print_core.o \
		obj/util/print_misc.o \
		obj/util/slice_core.o \
		obj/util/slice_parse.o \
		obj/util/slice_str.o \
		obj/util/tty.o

HDRS += src/util/private.h \
		src/util/util.h