OBJS += obj/parser/cmd_builder_argv.o \
		obj/parser/cmds_from_words.o \
		obj/parser/grammar.o \
		obj/parser/insert_vars.o \
		obj/parser/word_builder.o \
		obj/parser/word_core.o \
		obj/parser/words_from_slice.o

HDRS += src/parser/parser.h \
		src/parser/private.h