OBJS += obj/parser/grammar.o \
		obj/parser/insert_vars.o \
		obj/parser/iter_cmd_args.o \
		obj/parser/parser.o \
		obj/parser/word_builder.o \
		obj/parser/words.o

HDRS += src/parser/parser.h \
		src/parser/private.h