OBJS += obj/execution/run_cmd.o \
		obj/execution/child.o \
		obj/execution/check_heredoc.o \
		obj/execution/get_path_cmd.o \
		obj/execution/input_redirection.o \
		obj/execution/output_redirection.o \
		obj/execution/parent.o

HDRS += src/execution/execution.h