OBJS +=	obj/builtin_pwd.o \
		obj/builtin_env.o \
		obj/env.o \
		obj/libms.o \
		obj/main.o \
		obj/slice_core.o \
		obj/slice_str.o \
		obj/util_print_core.o \
		obj/util_print_misc.o \
		obj/vars.o

HDRS += src/builtin.h \
		src/env.h \
		src/slice.h \
		src/util_print.h \
		src/util.h \
		src/vars.h
